### ISSUE TITLE
Mod not working for 1.19.3?

### ISSUE THREAD

**Issue by KateReller** [kevinthegreat1/ColorfulConcrete-Fabric#2]
When using the command `/data merge block ~ ~ ~ {Color:[color]}` on a concrete block, the server says `The target block is not a block entity.`
The command `/data merge block ~ ~ ~ {Color:[color]}` reports `[Player] has the following entity data: {id: "minecraft:white_concrete", Count: 1b}` 
No sign of the color in there.

Logs: https://mclo.gs/RyZeQK9

**Comment by kevinthegreat1** [comment]
You need to use a `Colorful Concrete Block`, not the normal concrete block. Also, the `~ ~ ~` should be replaced with the pos of the block you're trying to modify.

**Comment by kevinthegreat1** [comment]
If you have more similar issues, feel free to reopen the issue.
